### ISSUE TITLE
Image width and height are not equal

### ISSUE THREAD

**Issue by SaulZhang** [richzhang/PerceptualSimilarity#45]
It seems that the code can't calculate the metric on the images with unequal width and height, can it be expanded to calculate images of various sizes?

**Comment by richzhang** [comment]
I think it should work out of the box

```
model = models.PerceptualLoss(model='net-lin', net='vgg', use_gpu=False, spatial=False)

H,W = 179, 32
dummy = torch.zeros(1,3,H,W)
print(model(dummy, dummy).item())
```

**Comment by SaulZhang** [comment]
Thanks for your answer, it does work in the example you provided. After my testing as the test_network.py script settings, I found that this problem is mainly caused by the setting of {net/spatial} parameter.
```python
model = models.PerceptualLoss(model='net-lin', net='alex', use_gpu=False, spatial=True)
H,W = 160, 64
dummy = torch.zeros(1,3,H,W)
```
the error information as follow:
`RuntimeError: The size of tensor a (61) must match the size of tensor b (58) at non-singleton dimension 3`

**Comment by richzhang** [comment]
Got it. I pushed a change to do resizing in both dimensions. Let me know if it works. Keep in mind the features in each layer will not necessarily be well-aligned in these cases

**Comment by khitish19** [comment]
The issue still persists for me. I was trying **compute_dists_pair.py** and got the same error when the image height and width were different but it all worked fine when I resize them to have same height and weight.

The error looks like this:
`RuntimeError: The size of tensor a (13) must match the size of tensor b (15) at non-singleton dimension 3`

**Comment by be42day** [comment]
The two images must be in the same size
